[project]
name = "anubis"
version = "0.1.0"
dependencies = [
    "python-dotenv",
    "discord.py",
    "bot-core @ https://github.com/python-discord/bot-core/archive/refs/tags/v8.2.1.zip",
    "aiohttp",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
