name: "Python CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@570079218747889f03eafe6ef14f855635ecbdee

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@570079218747889f03eafe6ef14f855635ecbdee

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10", "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@570079218747889f03eafe6ef14f855635ecbdee
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
