name: "Python CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@c194ec59628447c17718ee155e52060ef92dc406

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@c194ec59628447c17718ee155e52060ef92dc406

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10", "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@c194ec59628447c17718ee155e52060ef92dc406
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
